language: bash

services: docker

env:
  - VARIANT=base
  - VARIANT=node-8
  - VARIANT=node-9
  
before_script:
  - cd "$VARIANT"
  - image="richardregeer/web-development:${VARIANT}"
 
script:
  - docker build -t "$image" .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push "$image"

after_script:
- docker images