#!/bin/bash

if [ "$LANGUAGE" = "php" ]; then
  cp -Rv ${LANGUAGE}/etc/* "$VARIANT"
  cp -Rv ${LANGUAGE}/phpinfo "$VARIANT"/

  echo "Copied docker files for ${LANGUAGE}"
else
  echo "No files to copy for language ${LANGUAGE}"
fi