#!/bin/bash

if [ "$LANGUAGE" = "php" ]; then
  cp -R -v ${LANGUAGE}/etc/* "$VARIANT"
  cp -R -v ${LANGUAGE}/example/* "$VARIANT"

  echo "Copied docker files for ${LANGUAGE}"
else
  echo "No files to copy for language ${LANGUAGE}"
fi